config/routes.rb
Rails.application.routes.draw do
  #Splash   
  get 'welcome/index'
  root to: "welcome#index"  

  #Users
  get "/users/signup", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"  

  #Sessions
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy" 
  post "/sessions", to: "sessions#create"  

  #Events
  get 'events', to: "events#index", as: "events"
  get 'events/new', to: "events#new", as: "new_event"  
  post '/events', to:'events#create' 
  get '/events/:id', to: 'events#show', as: "event"   
  get '/events/:id/edit', to: 'events#edit', as: "edit_event"
  patch '/events/:id', to: 'events#update'
  delete '/events/:id', to: "events#destroy"

  #Events
  # get 'event/:id/, to: "reservations#new" 
  post '/events/:id/reservations', to:'reservations#create', as: "reservations" 
  get '/events/:event_id/reservations/:id/edit', to: 'reservations#edit', as: "edit_reservation"
  patch '/events/:event_id/reservations/:id', to: 'reservations#update'
  delete '/events/:event_id/reservations/:id', to: "reservations#destroy", as: "delete_reservation"  

  #Photos
  get 'photos/index', to: "photos#index", as: "photos"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, foreign_key: 'host_id'
  has_many :reservations, dependent: :destroy
  has_secure_password

  validates :first_name,
            presence:   true,
            length:   { maximum: 255 }
  validates :last_name,
            presence:   true,
            length:   { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false },
            length:     { maximum: 255 }
  VALID_PASSWORD_REGEX = /[a-zA-Z0-9]+/
  validates :password,
            presence:   true,
            length:     { minimum: 8 },
            allow_blank: true  

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show, :edit, :update]  
  before_action :logged_out?, only: [:new, :create]
  
  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Successfully created user"
      login(@user)
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      redirect_to new_user_path
     end
   end

  def show
    @user = User.find_by_id(params[:id])
    # events user is hosting
    # user >> reservations  >> events
    # user.events events where user.id is host_id
    @hosted_events = @user.events
    # events user is attending
    @attending_events = @user.reservations.map { |r|  Event.find(r.event_id) }.uniq
  end 

  def edit
    if current_user == set_user
      render :edit
    else
      flash[:error] = @user.errors.full_messages.join(", ")
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "Successfully Updated Profile"
    else
      flash[:error] = @user.errors.full_messages.join(", ")
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user == @user
      @user.destroy
      flash[:notice] = "Successfully deleted user #{@user.last_name}"
      redirect_to root_path
    else
      flash[:notice] = "You can't delete that user."
      redirect_to user_path(@user)
    end
  end  

  def events_index
    @user = User.find(params[:id])
    @events = @user.events_indexs
  end  

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    user_id = params[:id] || current_user.id
    @user = User.find(user_id)
  end           
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="jumbotron">
  <h1><span>Edit Profile</span></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3" id="form">
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :first_name, "First Name", class: "control-label" %>
          <%= f.text_field :first_name, :required => true, class: "form-control", placeholder: "First Name" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, "Last Name", class: "control-label" %>
          <%= f.text_field :last_name, :required => true, class: "form-control", placeholder: "Last Name" %>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email", class: " control-label" %>
          <%= f.text_field :email, :required => true, class: "form-control", placeholder: "email address" %>
        </div>
        <div class="form-group">
          <%= f.label :password, "Password", class: "control-label" %>
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>   
        <div class="form-group">
          <%= f.submit "Submit", class: "btn btn-default  center-bl form-control" %>
        </div>
      <% end %>
    </div>  
  </div>
</div>  

app/views/users/new.html.erb
<div class="jumbotron">
  <h1><span>Sign Up</span></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3" id="form">
      <%= form_for @user, url: "/users", method: "post" do |f| %>
        <div class="form-group">
          <%= f.label :first_name, "First Name", class: "control-label" %>
          <%= f.text_field :first_name, :required => true, class: "form-control", placeholder: "First Name" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, "Last Name", class: "control-label" %>
          <%= f.text_field :last_name, :required => true, class: "form-control", placeholder: "Last Name" %>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email", class: " control-label" %>
          <%= f.text_field :email, :required => true, class: "form-control", placeholder: "email address" %>
        </div>
        <div class="form-group">
          <%= f.label :password, "Password", class: "control-label" %>
          <%= f.password_field :password, :required => true, class: "form-control", placeholder: "Your Password" %>
        </div>  
        <div class="form-group">
          <%= f.label :password, "Password Confirmation", class: "control-label" %>
          <%= f.password_field :password_confirmation, :required => true, class: "form-control", placeholder: "Confirm Password" %>
        </div>
        <div class="form-group">
          <%= f.submit "Submit", class: "btn btn-default  center-bl form-control" %>
        </div>
      <% end %>  
    </div>
  </div>
</div>    

app/views/users/show.htm.erb
<h1>Profile Page</h1>
<div>
  Welcome, <%= @user.email %>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1><span>Profile</span></h1>
</div>
<section id="user">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-lg-offset-0">
          <h2><strong>Profile Page</strong></h2>
          <div class="container">
            <p>Welcome, <%= @user.first_name %> <%= @user.last_name %> to the OHANA Potluck App!</p>
            <ul>
              <li><b>Name: </b><%= @user.first_name %> <%= @user.last_name %></li>
              <li><b>Email: </b><%= @user.email %></li>
            </ul> 
            <p>You are now set to either host a potluck or attend one.</p>
            <p><strong>Creat a new <%= link_to "Event", new_event_path %></strong></p> 
            </div>
      </div>  
    </div>
<% if current_user == @user %>
      <div class="btn-group">
        <a href="/users/<%= @user.id %>/edit" class= "btn btn-default btn-lg">Edit</a>
      </div>
      <div class="btn-group">
        <%= button_to "Delete profile", @user, {method: :delete, data: {confirm: "Are you sure you want to delete your account #{@user.first_name}?"}, class: "btn btn-default btn-lg"}  %>
        <% end %> </section>        
<section id="user_potluck">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-lg-offset-0">
        <h2><strong>Potlucks Hosting</strong></h2>
        <!-- each loop using @hosted_events -->
        <% @hosted_events.each do |event| %>
          <ul>
            <li><%= event.date.strftime(' %B %d, %Y') %> - <%= link_to event.name, event_path(event.id) %></li>
          </ul>  
        <% end %> 
        <h2><strong>Potlucks Attending</strong></h2>
        <!-- each loop using @attending_events -->
        <% @attending_events.each do |event| %>
          <ul>
            <li><%= event.date.strftime(' %B %d, %Y') %> - <%= link_to event.name, event_path(event.id) %></li>
          </ul> 
        <% end %>         
      </div>
    </div>
  </div>       
</section>