config/routes.rb
Rails.application.routes.draw do
  #Splash   
  get 'welcome/index'
  root to: "welcome#index"  

  #Users
  get "/users/signup", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"  

  #Sessions
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy" 
  post "/sessions", to: "sessions#create"  

  #Events
  get 'events', to: "events#index", as: "events"
  get 'events/new', to: "events#new", as: "new_event"  
  post '/events', to:'events#create' 
  get '/events/:id', to: 'events#show', as: "event"   
  get '/events/:id/edit', to: 'events#edit', as: "edit_event"
  patch '/events/:id', to: 'events#update'
  delete '/events/:id', to: "events#destroy"

  #Events
  # get 'event/:id/, to: "reservations#new" 
  post '/events/:id/reservations', to:'reservations#create', as: "reservations" 
  get '/events/:event_id/reservations/:id/edit', to: 'reservations#edit', as: "edit_reservation"
  patch '/events/:event_id/reservations/:id', to: 'reservations#update'
  delete '/events/:event_id/reservations/:id', to: "reservations#destroy", as: "delete_reservation"  

  #Photos
  get 'photos/index', to: "photos#index", as: "photos"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :host, class_name: 'User', foreign_key:'host_id'  
  has_many :reservations, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in?, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :current_user?, only: [:edit, :destroy]

  def index
    @events = Event.order(:date)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Successfully created event."
      redirect_to event_path(@event)
    else
      flash[:error] = "Cannot create event."
      redirect_to new_event_path
    end
  end

  def show
      @event = Event.find_by_id(params[:id])
      @new_reservation = Reservation.new
      @reservation = @event.reservations
  end

  def edit
    @event = Event.find_by_id(params[:id])
    # if current_user.id == session[:user_id]
    render :edit
  end

  def update
    @event = Event.find_by_id(params[:id])
    # if current_user == @event.user
      if @event.update(event_params)
        flash[:notice] = "Successfully updated event."
        redirect_to event_path(@event)
      else
        flash[:error] = @event.errors.full_messages.join(", ")
        redirect_to edit_event_path(@event)
      end
    # else
      # redirect_to user_path(current_user)
    # end
  end

  def destroy
    @event = Event.find_by_id(params[:id])
      @event.destroy
      flash[:notice] = "Successfully deleted event."
      redirect_to events_path(current_user)
  end

  private

  def event_params
    valid = params.require(:event).permit(:name, :description, :place, :date, :host_id)
  
    date_format = "%m/%d/%Y %I:%M %p"
    # offset = DateTime.now.strftime
    valid[:date] = valid[:date] != "" ? DateTime.strptime(valid[:date], date_format).to_s : valid[:date]
    return valid
  end     

  def current_user?
    if Event.find(params[:id]).host_id == current_user.id
      return true
    else
      redirect_to events_path
      # render file: 'public/401.html', status: 401, layout: false 
    end  
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="jumbotron">
  <h1><span>Edit Event</span></h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3" id="form">
      <%= form_for @event do |f| %>    
        <div class="form-group">
          <%= f.label :name, "Name", class: "control-label" %>
          <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description", class: "control-label" %>
          <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
        </div>
        <div class="form-group">
          <%= f.label :place, "Place", class: "control-label" %>
          <%= f.text_field :place, class: "form-control", placeholder: "Place" %>
        </div>
        <div class="form-group">
          <%= f.label :date, "Date", class: "control-label" %>
          <div class='input-group date' id="datetimepicker">
            <%= f.text_field :date, {class: "form-control", placeholder: "Date"} %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>  
          <%= f.hidden_field :host_id, value: current_user.id %>   
        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-default  center-bl form-control" %>
        </div>
      <% end %> 
  </div>
</div> 
</div> 

app/views/events/index.html.erb
<div class="jumbotron">
  <h1><span>Events</span></h1>
</div>
<section id="potluck">
  <div class="container">
    <div class="row">
        <div class="col-lg-12 col-lg-offset-0">
          <div class="container">
            <h2><strong>Events</strong></h2>
              <% @events.each do |event| %>
                <ul>
                  <li><strong><%= event.date.strftime(' %B %d, %Y') %> - <%= link_to event.name, event_path(event.id) %></strong></li>
                </ul>  
              <% end %>
              <p class="new-event">Create a <%= link_to "New Event", new_event_path %>.</p>
          </div>  
        </div>
      </div>  
  </div>
</section>        

app/views/events/new.html.erb
<div class="jumbotron">
  <h1><span>New Event</span></h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3" id="form">
      <%= form_for @event do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name", class: "control-label" %>
          <%= f.text_field :name, :required => true, class: "form-control", placeholder: "Name" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description", class: "control-label" %>
          <%= f.text_area :description, :required => true, class: "form-control", placeholder: "Description" %>
        </div>
        <div class="form-group">
          <%= f.label :place, "Place", class: "control-label" %>
          <%= f.text_field :place, :required => true, class: "form-control", placeholder: "Place" %>
        </div>
        <div class="form-group">
          <%= f.label :date, "Date", class: "control-label" %>
          <div class='input-group date' id="datetimepicker">
            <%= f.text_field :date, {class: "form-control", placeholder: "Date"} %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
        <%= f.hidden_field :host_id, value: current_user.id  %>   
        <div class="form-group">
          <%= f.submit "Submit", class: "btn btn-default  center-bl form-control" %>
        </div>
      <% end %> 
    </div>
  </div>     
</div>

app/views/events/show.html.erb
<div class="jumbotron">
  <h1><span><%= @event.name %></span></h1>
</div>

<section id="potluck">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-lg-offset-0" id="name">
        <h2><strong>Potluck: <%= @event.name %></strong></h2>
          <ul>
            <li><strong>Description:</strong> <%= @event.description %></li>
            <li><strong>Place:</strong> <%= @event.place %></li>  
            <li><strong>Date:</strong> <%= @event.date.strftime('%A, %B %d, %Y') %></li>
            <li><strong>Time:</strong> <%= @event.date.strftime('%I:%M %p') %></li>
          </ul> 
      </div>
    </div>
  </div>  
  <div class="container"> 
    <div class="button">    
      <% if current_user %>
      <% if @event.host_id == current_user.id %>
        <div class="btn-group">
          <%= link_to "Edit", edit_event_path(@event.id), class: "btn btn-default btn-lg" %>
        </div>
        <div class="btn-group">
          <%= button_to "Delete", @event, { method: :delete, data: { confirm: "Are you sure you want to delete '#{@event.name}'?"}, class: 'btn btn-default btn-lg' } %>
        </div>           
      <% end %>  
      <% end %> 
    <div>
  </div> 
  <div class="col-md-12 col-lg-offset-0">
    <div class="panel panel-default" id="rsvp">     
      <h2 id="rsvp-text"><strong>RSVP for Potluck</strong></h2>
        <%= form_for @new_reservation do |f| %>
          <div class="form-group">
            <%= f.label :item_name, "Item", class: "control-label" %>
            <%= f.text_field :item_name, :required => true, class: "form-control", placeholder: "Item" %>
          </div>
          <div class="form-group">
            <%= f.label :item_description, "Description", class: "control-label" %>
            <%= f.text_field :item_description, :required => true, class: "form-control", placeholder: "Description" %>
          </div>  
          <div class="form-group">
            <%= f.label :item_image_url, "Image", class: "control-label" %>
            <%= f.text_field :item_image_url, :required => true, class: "form-control", placeholder: "Image" %>
          </div>  
            <%= f.hidden_field :event_id, :value => @event.id %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
          <div class="form-group">
            <%= f.submit "Submit", class: "btn btn-default  center-bl form-control" %>
          </div>
        <% end %> 
    </div> 
  </div>    
</section>
<section class="menu">
  <div class="container">
    <div class="col-lg-12 col-lg-offset-1">
      <div class="row">
        <h2 id="menu-text"><strong>Menu</strong></h2>
          <% @reservation.each do |reservation| %>
            <ul>
              <li><strong>Item: <%= reservation.item_name %></strong></li> 
              <li><strong>Description: <%= reservation.item_description %></strong></li> 
              <li><img class="menu" src="<%= reservation.item_image_url %>"</li>
            </ul> 
              <% if current_user %>
              <% if reservation.user_id == current_user.id %>
                <div class="button">
                  <div class="btn-group">
                    <%= link_to "Edit",edit_reservation_path(@event, reservation),
                      { method: :get, class: 'btn btn-default btn-lg' } %>
                  </div>       
                  <div class="btn-group">
                    <%= button_to "Delete",delete_reservation_path(@event, reservation),
                      { method: :delete, class: 'btn btn-default btn-lg' } %>
                  </div>
                </div>              
              <% end %> 
              <% end %>
          <% end %>  
      </div>
    </div>  
  </div>   
</div>
</section> 
</div>     